# Generated by Django 4.2.4 on 2023-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_transfer_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
