# Generated by Django 4.2.4 on 2023-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_transfer_end_date_transfer_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='value',
        ),
    ]
